# Generated by Django 5.2.17 on 2026-09-28 14:24

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "收货区（未上架）"),
                            ("STORAGE", "货架"),
                        ],
                        default="STORAGE",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "operation_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("command", models.CharField(max_length=40)),
                ("payload_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(null=True)),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("source_ref", models.CharField(blank=True, max_length=120)),
                ("created_by", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("qty_ordered", models.IntegerField()),
                ("requested_expiry", models.DateField(blank=True, null=True)),
                ("qty_unallocated", models.IntegerField(default=0)),
                ("qty_cancelled", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inventory.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNPAID", "客户未付款"),
                            ("CUSTOMER_REQUEST", "客户要求"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operation",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellations",
                        to="inventory.orderline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_allocated", models.IntegerField()),
                ("qty_shipped", models.IntegerField(default=0)),
                ("qty_released", models.IntegerField(default=0)),
                ("location_code", models.CharField(max_length=40)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="inventory.orderline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.owner"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name_zh", models.CharField(blank=True, max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("base_unit", models.CharField(default="EA", max_length=10)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sellable", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                ("row_version", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.owner",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("created_by", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptNoticeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("qty_expected", models.IntegerField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("external_lot", models.CharField(blank=True, max_length=80)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inventory.receiptnotice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RESERVE", "接单占用（未选货位）"),
                            ("CONVERT", "转为具体分配"),
                            ("ALLOCATE", "分配到批次/货位"),
                            ("CONSUME", "发货消耗"),
                            ("RELEASE", "取消释放"),
                        ],
                        max_length=10,
                    ),
                ),
                ("qty", models.IntegerField()),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="inventory.allocation",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operation",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_entries",
                        to="inventory.orderline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="inventory.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("PENDING_INSPECTION", "待检"),
                            ("AVAILABLE", "合格"),
                            ("HOLD", "冻结"),
                            ("DAMAGED", "不合格"),
                        ],
                        max_length=20,
                    ),
                ),
                ("on_hand", models.IntegerField(default=0)),
                ("allocated", models.IntegerField(default=0)),
                ("row_version", models.IntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.owner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="allocation",
            name="balance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="inventory.stockbalance",
            ),
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("RECEIPT", "收货"), ("OPENING", "期初导入")],
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(max_length=80)),
                ("external_lot", models.CharField(blank=True, max_length=80)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockbalance",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.stocklot"
            ),
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_received", models.IntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("PENDING_INSPECTION", "待检"),
                            ("AVAILABLE", "合格"),
                            ("HOLD", "冻结"),
                            ("DAMAGED", "不合格"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_code", models.CharField(max_length=40)),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operation",
                    ),
                ),
                (
                    "notice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="inventory.receiptnoticeline",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OPENING", "期初"),
                            ("RECEIPT", "收货"),
                            ("MOVE_OUT", "移出"),
                            ("MOVE_IN", "移入"),
                            ("CONDITION_OUT", "状态转出"),
                            ("CONDITION_IN", "状态转入"),
                            ("SHIP", "发货"),
                        ],
                        max_length=15,
                    ),
                ),
                ("qty", models.IntegerField()),
                ("location_code", models.CharField(max_length=40)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("PENDING_INSPECTION", "待检"),
                            ("AVAILABLE", "合格"),
                            ("HOLD", "冻结"),
                            ("DAMAGED", "不合格"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_doc", models.CharField(blank=True, max_length=80)),
                ("source_line", models.CharField(blank=True, max_length=40)),
                ("actor", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business_date", models.DateField()),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockbalance",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_lines",
                        to="inventory.allocation",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inventory.shipment",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="uniq_order_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="uniq_product_owner_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.UniqueConstraint(
                fields=("order", "line_no"), name="uniq_order_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_ordered__gt", 0)), name="line_qty_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_unallocated__gte", 0)),
                name="line_unalloc_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_cancelled__gte", 0)), name="line_cancel_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="productavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("sellable__gte", 0)), name="pa_sellable_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="productavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)), name="pa_reserved_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="productavailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("sellable"))),
                name="pa_reserved_le_sellable",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptnotice",
            constraint=models.UniqueConstraint(
                fields=("owner", "number"), name="uniq_notice_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qty_shipped__gte", 0),
                    ("qty_released__gte", 0),
                    (
                        "qty_allocated__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("qty_shipped"), "+", models.F("qty_released")
                        ),
                    ),
                ),
                name="alloc_open_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                fields=("product", "source_type", "source_ref"), name="uniq_lot_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("owner", "product", "lot", "location", "condition"),
                name="uniq_balance_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand__gte", 0)), name="bal_on_hand_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated__gte", 0)), name="bal_allocated_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated__lte", models.F("on_hand"))),
                name="bal_allocated_le_on_hand",
            ),
        ),
    ]
