# Generated by Django 5.2.17 on 2026-09-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stock', '库存表（期初库存）'), ('inspection', '验货纸（收货预告）'), ('pdf_order', 'PDF 送货单（出库订单）')], max_length=20)),
                ('file_name', models.CharField(max_length=200)),
                ('file_sha256', models.CharField(max_length=64)),
                ('owner_code', models.CharField(max_length=40)),
                ('external_doc_no', models.CharField(blank=True, max_length=80)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('export_basis', models.CharField(blank=True, max_length=20)),
                ('lines', models.JSONField(default=list)),
                ('batch_errors', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PREVIEW', '待确认'), ('POSTED', '已入账')], default='PREVIEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=40)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='source_line',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
