# Generated by Django 5.2.17 on 2026-09-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_import_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numbers', models.CharField(max_length=200)),
                ('ship_to', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('delivery_time', models.CharField(max_length=60)),
                ('pallet_count', models.PositiveSmallIntegerField()),
                ('created_by', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(related_name='pallet_sheets', to='inventory.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.owner')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pallet_count__gte', 1), ('pallet_count__lte', 99)), name='pallet_count_1_99')],
            },
        ),
    ]
